### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by psashv** [atom/image-view#147] opened 2017-08-11 11:40 UTC
[Enter steps to reproduce:]

/cc https://github.com/atom/tabs/issues/444#issuecomment-321207395

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.61.2

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At C:\Users\Николай\AppData\Local\atom\app-1.19.0\resources\app\node_modules\event-kit\lib\emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:77:21)
    at ImageEditorView.onDidLoad (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/image-view/lib/image-editor-view.js:154:33)
    at ImageEditorStatusView.updateImageSize (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/image-view/lib/image-editor-status-view.js:88:58)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/image-view/lib/image-editor-status-view.js:46:19
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:493:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane-container.js:284:26)
    at Pane.module.exports.Pane.setActiveItem (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:339:22)
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:560:20)
    at Pane.module.exports.Pane.moveItemToPane (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:676:25)
    at Object.end (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/tabs/lib/layout.js:63:22)
    at HTMLLIElement.TabView.element.ondragend (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/tabs/lib/tab-view.js:62:29)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by Ben3eeE** [comment] 2017-08-11 11:49
Refs: https://github.com/atom/tabs/issues/444#issuecomment-321207395 for steps to reproduce

**Comment by lee-dohm** [comment] 2017-08-22 20:20
Thank you for your submission!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2017-08-22 20:20 UTC
Labels: bug, triaged, uncaught-exception
