### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/floatec/Library/Application Supp...

### ISSUE THREAD

**Issue by floatec** [atom/image-view#43] opened 2015-10-09 07:17 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [image-view](https://github.com/atom/image-view) package, v0.54.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/floatec/Library/Application Support/com.github.atom.ShipIt/update.LQZXeOV'

```
At ATOM_SHELL_ASAR.js:118

Error: ENOENT: no such file or directory, lstat '/Users/floatec/Library/Application Support/com.github.atom.ShipIt/update.LQZXeOV'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1449:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:108:13)
    at tryFile (module.js:104:22)
    at tryExtensions (module.js:114:20)
    at tryPackage (module.js:92:31)
    at Function.Module._findPath (module.js:155:20)
    at Module._resolveFilename (module.js:332:25)
    at Function.Module._resolveFilename (/Users/floatec/Library/Application Support/com.github.atom.ShipIt/update.LQZXeOV/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/floatec/Library/Application Support/com.github.atom.ShipIt/update.LQZXeOV/Atom.app/Contents/Resources/app.asar/node_modules/image-view/lib/image-editor-status-view.js:6:10)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-10-09 11:46
Hi @floatec, this seems like a duplicate of atom/atom#7399, so I'm going to close this in favor of that.  Could you also share what you were doing when this happened on atom/atom#7399?  Thanks.

**Closed by 50Wliu** 2015-10-09 11:46 UTC
