### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, stat '~/codefellows\week4\Codographic-Memory\inst...

### ISSUE THREAD

**Issue by esthersuk** [atom/image-view#126] opened 2017-06-26 21:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.61.2

### Stack Trace

Uncaught Error: EPERM: operation not permitted, stat 'C:\Users\Esther\codefellows\week4\Codographic-Memory\instructionImgs\step2.png'

```
At fs.js:992

Error: EPERM: operation not permitted, stat 'C:\Users\Esther\codefellows\week4\Codographic-Memory\instructionImgs\step2.png'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Proxy.fs.statSync (ELECTRON_ASAR.js:275:16)
    at new ImageEditorView (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/image-view/lib/image-editor-view.js:39:48)
    at ImageEditor.get (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/image-view/lib/image-editor.js:180:33)
    at ImageEditor.get (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/image-view/lib/image-editor.js:174:24)
    at ViewRegistry.module.exports.ViewRegistry.createView (~/AppData/Local/atom/app-1.18.0/resources/app/src/view-registry.js:105:41)
    at ViewRegistry.module.exports.ViewRegistry.getView (~/AppData/Local/atom/app-1.18.0/resources/app/src/view-registry.js:88:27)
    at atom-pane.PaneElement.activeItemChanged (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane-element.js:138:29)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.setActiveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:316:28)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:471:27)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.2 
linter 2.0.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
```

**Comment by 50Wliu** [comment] 2017-07-13 01:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #74. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-07-13 01:13 UTC
