### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Downloads/media/cover/003.Zayn

### ISSUE THREAD

**Issue by kangdain** [atom/image-view#96] opened 2017-04-08 05:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.60.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/Dain_Kang/Downloads/media/cover/003.Zayn

**Comment by 50Wliu** [comment] 2017-04-09 16:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #74. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-04-09 16:29 UTC
