### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Developer/w3man-tempus/electron/dist/t...

### ISSUE THREAD

**Issue by masterX244** [atom/image-view#79] opened 2017-01-27 10:07 UTC
[Enter steps to reproduce below:]

1. Open any picture in a tab in the editor
2. Delete the picture with the File manager
3. try to close that tab

Expected: Being able to close the tab

Gotten: Tab that is unclosable and spams red errors on each click on it

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [image-view](https://github.com/atom/image-view) package, v0.60.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/tgo/Developer/w3man-tempus/electron/dist/tempus.png'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/Users/tgo/Developer/w3man-tempus/electron/dist/tempus.png'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at ImageEditorView.module.exports.ImageEditorView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/image-view/lib/image-editor-view.js:96:34)
    at ImageEditorView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at ImageEditorView.ScrollView [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new ImageEditorView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/image-view/lib/image-editor-view.js:16:52)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:134:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:84:21)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:132:29)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:437:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:681:19)
```

### Commands

```
     -6:25.7.0 core:save (input.hidden-input)
  4x -6:20.7.0 core:backspace (input.hidden-input)
     -6:15.9.0 core:save (input.hidden-input)
     -1:09.0 editor:newline (input.hidden-input)
     -1:04.6.0 core:move-left (input.hidden-input)
     -1:04.4.0 editor:newline (input.hidden-input)
     -1:03.9.0 core:move-right (input.hidden-input)
     -1:03.6.0 editor:newline (input.hidden-input)
  4x -0:59.4.0 core:backspace (input.hidden-input)
     -0:56.8.0 core:move-left (input.hidden-input)
  2x -0:55.7.0 core:move-right (input.hidden-input)
  4x -0:51.9.0 core:backspace (input.hidden-input)
     -0:47 core:move-right (input.hidden-input)
     -0:45.1.0 core:backspace (input.hidden-input)
  2x -0:44.6.0 core:move-right (input.hidden-input)
     -0:42.5.0 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "wrap-guide",
      "spell-check",
      "language-mustache"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".codekit-cache",
      "bower_components",
      "node_modules",
      "ext",
      "build"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "warnOnLargeFileLimit": 2
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.17 (active)
atom-handlebars, v1.3.0 (active)
custom-title, v1.0.1 (active)
language-latex, v1.0.0 (active)
latexer, v0.3.0 (active)
minimap, v4.26.7 (active)
minimap-git-diff, v4.3.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (active)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2017-01-27 21:39
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/image-view/issues/74. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-01-27 21:39 UTC
Labels: bug, uncaught-exception
