### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/ionic-app-2\resources\android\icon\dra...

### ISSUE THREAD

**Issue by leofrancomachado** [atom/image-view#94] opened 2017-03-25 15:57 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.60.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\leona\ionic-app-2\resources\android\icon\drawable-xhdpi-icon.png'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat 'C:\Users\leona\ionic-app-2\resources\android\icon\drawable-xhdpi-icon.png'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at ImageEditorView.module.exports.ImageEditorView.initialize (/app.asar/node_modules/image-view/lib/image-editor-view.js:96:34)
    at /app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at /app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at /app.asar/node_modules/image-view/lib/image-editor-view.js:16:52)
    at ViewRegistry.module.exports.ViewRegistry.createView (/app.asar/src/view-registry.js:134:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/app.asar/src/view-registry.js:84:21)
    at /app.asar/src/pane-element.js:180:37)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:589:20)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
     -1:38.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:48.7.0 pane:reopen-closed-item (li.texteditor.tab.sortable.right-clicked)
```

### Non-Core Packages

```
atom-typescript 11.0.1 
busy-signal 1.3.0 
file-icons 2.1.1 
file-type-icons 1.3.3 
intentions 1.1.2 
linter 2.1.2 
linter-ui-default 1.2.1 
seti-icons 1.4.3 
```

**Comment by rsese** [comment] 2017-03-27 17:34
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/image-view/issues/74. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-27 17:34 UTC
