### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/ut-coding-bootcamp/trivia1/Giphy/Sand....

### ISSUE THREAD

**Issue by KatieKosh** [atom/image-view#84] opened 2017-02-27 04:58 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.60.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/kathrynkoshinski/ut-coding-bootcamp/trivia1/Giphy/Sand.jpg'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/Users/kathrynkoshinski/ut-coding-bootcamp/trivia1/Giphy/Sand.jpg'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at ImageEditorView.module.exports.ImageEditorView.initialize (/app.asar/node_modules/image-view/lib/image-editor-view.js:96:34)
    at /app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at /app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at /app.asar/node_modules/image-view/lib/image-editor-view.js:16:52)
    at ViewRegistry.module.exports.ViewRegistry.createView (/app.asar/src/view-registry.js:134:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/app.asar/src/view-registry.js:84:21)
    at /app.asar/src/pane-element.js:194:25)
    at /app.asar/src/pane-element.js:51:55)
    at /app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:852:27)
    at /app.asar/node_modules/notifications/lib/notification-element.js:298:40)
    at /app.asar/node_modules/notifications/lib/notification-element.js:256:19)
    at /app.asar/node_modules/notifications/lib/notification-element.js:59:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Notification.module.exports.Notification.dismiss (/app.asar/src/notification.js:79:27)
    at /app.asar/node_modules/notifications/lib/notification-element.js:260:25)
    at /app.asar/node_modules/notifications/lib/notification-element.js:149:26)
```

### Commands

```
     -9:56.5.0 core:backspace (input.hidden-input)
     -9:55.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -9:55.1.0 editor:newline (input.hidden-input)
     -9:47.1.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -9:40.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -9:40.8.0 editor:newline (input.hidden-input)
     -9:35.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -9:23.7.0 core:copy (span.syntax--constant.syntax--other.syntax--color.syntax--rgb-value.syntax--css)
     -9:20.9.0 core:paste (div.line.cursor-line)
     -9:18 core:save (input.hidden-input)
  2x -8:11.3.0 open-in-browser:open (div.line)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
color-picker 2.2.5 
compare-files 0.8.0 
emmet 2.4.3 
file-icons 2.0.15 
git-log 0.4.1 
git-time-machine 1.5.4 
linter-flake8 2.1.4 
markdown-preview-plus 2.4.1 
markdown-writer 2.6.3 
merge-conflicts 1.4.4 
minimap 4.26.8 
open-in-browser 0.4.7 
pigments 0.39.0 
split-diff 1.1.1 
```

**Comment by rsese** [comment] 2017-02-27 05:21
Seems like it could be a duplicate of https://github.com/atom/image-view/issues/74?

@KatieKosh it looks like the `Steps to Reproduce` section wasn't filled out, can you confirm your steps to reproduce?

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by Ben3eeE** [comment] 2017-03-02 23:03
I agree that this is a duplicate of #74. @KatieKosh Please let us know if you have steps to reproduce that are different from what is described in https://github.com/atom/image-view/issues/74#issuecomment-283734866 and we can reopen 😀

**Closed by Ben3eeE** 2017-03-02 23:03 UTC
Labels: more-information-needed
