### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/projects/todoApp/JsonApp/Screenshots/a...

### ISSUE THREAD

**Issue by prancky** [atom/image-view#148] opened 2017-08-14 03:26 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.61.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/prancky/projects/todoApp/JsonApp/Screenshots/android/login-2.png'

```
At fs.js:912

Error: ENOENT: no such file or directory, stat '/Users/prancky/projects/todoApp/JsonApp/Screenshots/android/login-2.png'
    at fs.statSync (fs.js:912:18)
    at Proxy.fs.statSync (ELECTRON_ASAR.js:280:16)
    at new ImageEditorView (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor-view.js:39:48)
    at ImageEditor.get (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor.js:180:33)
    at ImageEditor.get (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor.js:174:24)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:92:41)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:75:27)
    at HTMLElement.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:200:25)
    at HTMLElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:53:55)
    at HTMLElement.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:117:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:913:33)
    at NotificationElement.module.exports.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:294:46)
    at NotificationElement.module.exports.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:252:25)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:54:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Notification.module.exports.Notification.dismiss (/Applications/Atom.app/Contents/Resources/app/src/notification.js:79:33)
    at NotificationElement.module.exports.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:256:31)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:145:32)
```

### Commands

```
  2x -0:26.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.17 
auto-detect-indentation 1.3.0 
autocomplete-paths 1.0.5 
compare-files 0.8.1 
console-log 1.10.0 
file-icons 2.1.10 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.69.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
lint 0.0.1 
local-history 4.3.0 
MagicPython 1.0.11 
nuclide 0.243.0 
nuclide-format-js 0.0.41 
react-native-snippets 0.3.0 
react-redux-snippets 0.1.6 
react-snippets 0.9.0 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
tree-view-search-bar 0.1.8 
```

**Comment by Ben3eeE** [comment] 2017-08-14 05:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/image-view/issues/74.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-14 05:56 UTC
Labels: duplicate
