### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Documents/twitchy_the_bot/img.png'

### ISSUE THREAD

**Issue by Harmiox** [atom/image-view#135] opened 2017-07-12 18:06 UTC

**Comment by 50Wliu** [comment] 2017-07-13 01:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #74. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-07-13 01:12 UTC
