### ISSUE TITLE
Image location within the window

### ISSUE THREAD

**Issue by JLCCI** [atom/image-view#71] opened 2016-08-30 14:48 UTC
The image viewer does not seem to play well with multiple tabs opened next to each other. When opening an image in of the tabs you can only see the background and you have to scroll right to see the image.

Perhaps the background should be scaled depending on the sub-window size or the image should automatically be centered? Having a tab with image is incredibly useful in any data visualization task within Atom.

![screenshot from 2016-08-30 23-40-11](https://cloud.githubusercontent.com/assets/18163728/18093645/856bce10-6f0b-11e6-83c8-02a8f9926915.png)

![screenshot from 2016-08-30 23-43-44](https://cloud.githubusercontent.com/assets/18163728/18093668/9dd6ee80-6f0b-11e6-97f8-f31dd4266a60.png)

**Comment by Ben3eeE** [comment] 2016-08-30 15:14
It seems you have zoom to fit mode active. Zoom to fit is broken in Atom 1.9 and will be fixed in Atom 1.10.

I am unable to reproduce this in Atom 1.10-beta7. Please let me know if you can reproduce this in Atom 1.10 once it is available or if you are already using the Atom 1.10-beta.

refs: https://github.com/atom/image-view/pull/58

**Closed** 2016-08-30 15:33 UTC
