### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/var/www/systemone/public/themes/labeach...

### ISSUE THREAD

**Issue by zachdyer** [atom/image-view#134] opened 2017-07-12 13:37 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.61.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/var/www/systemone/public/themes/labeachhomesearch.com/img/big_slider/banner1.jpg'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/var/www/systemone/public/themes/labeachhomesearch.com/img/big_slider/banner1.jpg'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Proxy.fs.statSync (ELECTRON_ASAR.js:275:16)
    at new ImageEditorView (/usr/share/atom/resources/app/node_modules/image-view/lib/image-editor-view.js:39:48)
    at ImageEditor.get (/usr/share/atom/resources/app/node_modules/image-view/lib/image-editor.js:180:33)
    at ImageEditor.get (/usr/share/atom/resources/app/node_modules/image-view/lib/image-editor.js:174:24)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app/src/view-registry.js:105:41)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app/src/view-registry.js:88:27)
    at atom-pane.PaneElement.itemRemoved (/usr/share/atom/resources/app/src/pane-element.js:186:37)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app/src/pane.js:613:26)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:685:22)
    at TabBarView.module.exports.TabBarView.closeTab (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:340:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:228:25)
```

### Commands

```
     -1:41.3.0 tree-view:move (span.name.icon.icon-file-directory)
     -1:38.7.0 core:move-left (input.hidden-input)
     -1:36.1.0 core:confirm (input.hidden-input)
     -1:11.5.0 tree-view:move (span.name.icon.icon-file-media)
     -1:02.5.0 core:copy (input.hidden-input)
     -0:33.3.0 tree-view:move (span.name.icon.icon-file-media)
     -0:31 core:paste (input.hidden-input)
     -0:30.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.2.5 
```

**Comment by 50Wliu** [comment] 2017-07-13 01:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #74. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-07-13 01:12 UTC
Labels: duplicate
